// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="./custom.d.ts" />
// tslint:disable
// eslint:disable
/**
 * Addicted Proxy
 * Provide a full system to search and download subtitles from Addi7ed website.
 *
 * OpenAPI spec version: 1.1.1
 *
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
  csv: ",",
  ssv: " ",
  tsv: "\t",
  pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
  (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
  url: string;
  options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
  protected configuration?: Configuration;

  constructor(
    configuration?: Configuration,
    protected basePath: string = BASE_PATH,
    protected fetch: FetchAPI = isomorphicFetch
  ) {
    this.configuration = configuration;
    if (configuration) {
      this.basePath = configuration.basePath || this.basePath;
    }
  }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
  constructor(public field: string, msg?: string) {
    super(msg);
  }
}

/**
 * Episode information
 * @export
 * @interface EpisodeDto
 */
export interface EpisodeDto {
  /**
   * Season of the episode
   * @type {number}
   * @memberof EpisodeDto
   */
  season?: number;
  /**
   * Number of the episode
   * @type {number}
   * @memberof EpisodeDto
   */
  number?: number;
  /**
   * Title of the episode
   * @type {string}
   * @memberof EpisodeDto
   */
  title?: string;
  /**
   * For which show
   * @type {string}
   * @memberof EpisodeDto
   */
  show?: string;
  /**
   * When was the Episode discovered
   * @type {Date}
   * @memberof EpisodeDto
   */
  discovered?: Date;
}

/**
 * Returns when there is an error
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
  /**
   *
   * @type {string}
   * @memberof ErrorResponse
   */
  error?: string;
}

/**
 * Used for different Media Center/Subtitle searchers
 * @export
 * @interface QueryRequest
 */
export interface QueryRequest {
  /**
   * Name of the show
   * @type {string}
   * @memberof QueryRequest
   */
  show: string;
  /**
   * Episode number
   * @type {number}
   * @memberof QueryRequest
   */
  episode: number;
  /**
   * Season number
   * @type {number}
   * @memberof QueryRequest
   */
  season: number;
  /**
   * Name of the file for which you want subtitle, it help find a version of the subtitle that matches it
   * @type {string}
   * @memberof QueryRequest
   */
  fileName?: string;
  /**
   * 3 or 2 letter code of the language
   * @type {string}
   * @memberof QueryRequest
   */
  languageISO: string;
}

/**
 * Use for the website to provide easy search for the user
 * @export
 * @interface SearchRequest
 */
export interface SearchRequest {
  /**
   * Search for specific subtitle
   * @type {string}
   * @memberof SearchRequest
   */
  search?: string;
  /**
   * Language of the subtitle
   * @type {string}
   * @memberof SearchRequest
   */
  language?: string;
}

/**
 *
 * @export
 * @interface SearchResponse
 */
export interface SearchResponse {
  /**
   * Matching subtitle for the filename and language
   * @type {Array<SubtitleDto>}
   * @memberof SearchResponse
   */
  matchingSubtitles?: Array<SubtitleDto>;
  /**
   *
   * @type {EpisodeDto}
   * @memberof SearchResponse
   */
  episode?: EpisodeDto;
}

/**
 *
 * @export
 * @interface SubtitleDto
 */
export interface SubtitleDto {
  /**
   * Unique Id of the subtitle
   * @type {string}
   * @memberof SubtitleDto
   */
  subtitleId?: string;
  /**
   * Version of the subtitle
   * @type {string}
   * @memberof SubtitleDto
   */
  version?: string;
  /**
   *
   * @type {boolean}
   * @memberof SubtitleDto
   */
  completed?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof SubtitleDto
   */
  hearingImpaired?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof SubtitleDto
   */
  corrected?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof SubtitleDto
   */
  hd?: boolean;
  /**
   * Url to download the subtitle
   * @type {string}
   * @memberof SubtitleDto
   */
  downloadUri?: string;
  /**
   * Language of the subtitle (in English)
   * @type {string}
   * @memberof SubtitleDto
   */
  language?: string;
  /**
   * When was the subtitle discovered in UTC
   * @type {Date}
   * @memberof SubtitleDto
   */
  discovered?: Date;
  /**
   * Number of times the subtitle was downloaded from the proxy
   * @type {number}
   * @memberof SubtitleDto
   */
  downloadCount?: number;
}

/**
 * Returned when the search wasn't formatted properly
 * @export
 * @interface WrongFormatResponse
 */
export interface WrongFormatResponse {
  /**
   *
   * @type {string}
   * @memberof WrongFormatResponse
   */
  error?: string;
  /**
   *
   * @type {string}
   * @memberof WrongFormatResponse
   */
  search?: string;
}

/**
 * SubtitlesApi - fetch parameter creator
 * @export
 */
export const SubtitlesApiFetchParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @summary Download specific subtitle
     * @param {string} subtitleId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    downloadSubtitle(subtitleId: string, options: any = {}): FetchArgs {
      // verify required parameter 'subtitleId' is not null or undefined
      if (subtitleId === null || subtitleId === undefined) {
        throw new RequiredError(
          "subtitleId",
          "Required parameter subtitleId was null or undefined when calling downloadSubtitle."
        );
      }
      const localVarPath = `/subtitles/download/{subtitleId}`.replace(
        `{${"subtitleId"}}`,
        encodeURIComponent(String(subtitleId))
      );
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * The routes are ratelimited to 15 call per seconds.
     * @summary Query for subtitle of a specific episode of a show
     * @param {QueryRequest} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    subtitlesQueryPost(body?: QueryRequest, options: any = {}): FetchArgs {
      const localVarPath = `/subtitles/query`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"QueryRequest" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Search for a specific episode
     * @param {SearchRequest} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    subtitlesSearchPost(body?: SearchRequest, options: any = {}): FetchArgs {
      const localVarPath = `/subtitles/search`;
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "POST" }, options);
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      localVarUrlObj.query = Object.assign(
        {},
        localVarUrlObj.query,
        localVarQueryParameter,
        options.query
      );
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search;
      localVarRequestOptions.headers = Object.assign(
        {},
        localVarHeaderParameter,
        options.headers
      );
      const needsSerialization =
        <any>"SearchRequest" !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.body = needsSerialization
        ? JSON.stringify(body || {})
        : body || "";

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * SubtitlesApi - functional programming interface
 * @export
 */
export const SubtitlesApiFp = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Download specific subtitle
     * @param {string} subtitleId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    downloadSubtitle(
      subtitleId: string,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
      const localVarFetchArgs = SubtitlesApiFetchParamCreator(
        configuration
      ).downloadSubtitle(subtitleId, options);
      return (
        fetch: FetchAPI = isomorphicFetch,
        basePath: string = BASE_PATH
      ) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response;
          } else {
            throw response;
          }
        });
      };
    },
    /**
     * The routes are ratelimited to 15 call per seconds.
     * @summary Query for subtitle of a specific episode of a show
     * @param {QueryRequest} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    subtitlesQueryPost(
      body?: QueryRequest,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<SearchResponse> {
      const localVarFetchArgs = SubtitlesApiFetchParamCreator(
        configuration
      ).subtitlesQueryPost(body, options);
      return (
        fetch: FetchAPI = isomorphicFetch,
        basePath: string = BASE_PATH
      ) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
    /**
     *
     * @summary Search for a specific episode
     * @param {SearchRequest} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    subtitlesSearchPost(
      body?: SearchRequest,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<SearchResponse> {
      const localVarFetchArgs = SubtitlesApiFetchParamCreator(
        configuration
      ).subtitlesSearchPost(body, options);
      return (
        fetch: FetchAPI = isomorphicFetch,
        basePath: string = BASE_PATH
      ) => {
        return fetch(
          basePath + localVarFetchArgs.url,
          localVarFetchArgs.options
        ).then((response) => {
          if (response.status >= 200 && response.status < 300) {
            return response.json();
          } else {
            throw response;
          }
        });
      };
    },
  };
};

/**
 * SubtitlesApi - factory interface
 * @export
 */
export const SubtitlesApiFactory = function (
  configuration?: Configuration,
  fetch?: FetchAPI,
  basePath?: string
) {
  return {
    /**
     *
     * @summary Download specific subtitle
     * @param {string} subtitleId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    downloadSubtitle(subtitleId: string, options?: any) {
      return SubtitlesApiFp(configuration).downloadSubtitle(
        subtitleId,
        options
      )(fetch, basePath);
    },
    /**
     * The routes are ratelimited to 15 call per seconds.
     * @summary Query for subtitle of a specific episode of a show
     * @param {QueryRequest} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    subtitlesQueryPost(body?: QueryRequest, options?: any) {
      return SubtitlesApiFp(configuration).subtitlesQueryPost(body, options)(
        fetch,
        basePath
      );
    },
    /**
     *
     * @summary Search for a specific episode
     * @param {SearchRequest} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    subtitlesSearchPost(body?: SearchRequest, options?: any) {
      return SubtitlesApiFp(configuration).subtitlesSearchPost(body, options)(
        fetch,
        basePath
      );
    },
  };
};

/**
 * SubtitlesApi - object-oriented interface
 * @export
 * @class SubtitlesApi
 * @extends {BaseAPI}
 */
export class SubtitlesApi extends BaseAPI {
  /**
   *
   * @summary Download specific subtitle
   * @param {string} subtitleId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SubtitlesApi
   */
  public downloadSubtitle(subtitleId: string, options?: any) {
    return SubtitlesApiFp(this.configuration).downloadSubtitle(
      subtitleId,
      options
    )(this.fetch, this.basePath);
  }

  /**
   * The routes are ratelimited to 15 call per seconds.
   * @summary Query for subtitle of a specific episode of a show
   * @param {QueryRequest} [body]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SubtitlesApi
   */
  public subtitlesQueryPost(body?: QueryRequest, options?: any) {
    return SubtitlesApiFp(this.configuration).subtitlesQueryPost(body, options)(
      this.fetch,
      this.basePath
    );
  }

  /**
   *
   * @summary Search for a specific episode
   * @param {SearchRequest} [body]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SubtitlesApi
   */
  public subtitlesSearchPost(body?: SearchRequest, options?: any) {
    return SubtitlesApiFp(this.configuration).subtitlesSearchPost(
      body,
      options
    )(this.fetch, this.basePath);
  }
}
