// tslint:disable
/**
 * Addicted Proxy
 * Provide a full system to search and download subtitles from Addi7ed website.
 *
 * OpenAPI spec version: 1.2.1
 *
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
